ktor:
  deployment:
    port: 8080
    host: 0.0.0.0
  application:
    modules:
      - com.d1onix.SerializationKt.configureSerialization
      - com.d1onix.ExposedKt.configureExposed
      - com.d1onix.RoutingKt.configureRouting
      - com.d1onix.DatabaseKt.configureDatabases

storage:
    driverClassName: "org.postgresql.Driver"
    jdbcURL: "jdbc:postgresql://localhost:5432/mydatabase"
    user: "myuser"
    password: "mypassword"